services:
  override-app:
    image: linux-do/override:latest
    container_name: override-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config.json:/app/config.json
    ports:
      - "8181:8181"
